/**
 * DEMO MODE banner. Shown while the prepared demo dataset loads and while
 * it is active. States plainly that results are precomputed for a prepared
 * (synthetic) scene and were NOT generated by live inference. The live AI
 * pipeline is untouched — demo data only fills the same display state.
 */
export default function DemoBanner({ mode, stage, error, meta, counts, onExit }) {
  if (mode === 'off') return null;

  return (
    <section className="card detect-section demo-banner" aria-live="polite">
      <div className="detect-head">
        <div>
          <h2>Demo Dataset — DEMO MODE</h2>
          <p className="sub">
            {mode === 'loading'
              ? (stage || 'Loading prepared demo image…')
              : 'Showing prepared results. No live AI inference ran for this data.'}
          </p>
        </div>
        <div className="detect-badges">
          <span className="badge badge-demo">▶ DEMO MODE — precomputed</span>
          {mode === 'active' && (
            <button className="btn small ghost" onClick={onExit}>Exit demo</button>
          )}
        </div>
      </div>

      {mode === 'loading' && (
        <div className="progress-bar"><div className="progress-fill anim" /></div>
      )}

      {error && <p className="alert-err">{error}</p>}

      {mode === 'active' && meta && (
        <div className="file-meta">
          <div className="meta-row"><span>Scene</span><strong>{meta.name} (synthetic, no real location)</strong></div>
          <div className="meta-row"><span>Image</span><strong>demo-aerial.png · {meta.image.width} × {meta.image.height} px · GSD {meta.gsd_m_per_px} m/px</strong></div>
          <div className="meta-row"><span>Contents</span><strong>{counts.parcels} parcels · {counts.buildings} buildings · {counts.features} features</strong></div>
        </div>
      )}

      <p className="warn-box">
        DEMO MODE: prepared demo image with precomputed results for presentation.
        The live AI pipeline is separate — these numbers were not generated by inference just now.
      </p>
    </section>
  );
}
