"""Convert Inria Aerial Image Labeling tiles into a YOLO detection dataset.

Reads 5000x5000 RGB + binary-mask TIFF pairs from data/inria_raw/
(<name>.tif + <name>_gt.tif, e.g. from the HuggingFace mirror
blanchon/INRIA-Aerial-Image-Labeling) and produces the Ultralytics YOLO
layout expected by tools/train_detector.py:

    data/dataset/
      data.yaml
      images/train/*.jpg  images/val/*.jpg
      labels/train/*.txt  labels/val/*.txt   # "0 cx cy w h" normalised

Strategy: cut each tile into 1000x1000 chips (5x5 = 25 chips/tile),
extract building boxes per chip with connected components on the mask.
The train/val split is BY SOURCE TILE (never mix chips of one tile across
splits) so validation measures cross-area generalisation, not memorisation.

Usage:
    python tools/prepare_inria.py
    python tools/train_detector.py check
"""

from __future__ import annotations

from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "inria_raw"
OUT = ROOT / "data" / "dataset"

CHIP = 1000
# Train on dense urban tiles, validate on held-out cities (incl. suburban).
TRAIN_TILES = ("austin1", "austin2", "chicago1", "chicago2")
VAL_TILES = ("kitsap1", "vienna1")
# At 0.3 m/px, 150 px^2 ~= 13.5 m^2 — below any real building, kills specks.
MIN_AREA_PX = 150

DATA_YAML = """# Inria-subset detector dataset (generated by tools/prepare_inria.py).
path: .
train: images/train
val: images/val

names:
  0: building
"""


def chip_boxes(mask_chip: np.ndarray) -> list[tuple[float, float, float, float]]:
    """Building boxes in chip pixels: connected components of the mask."""
    _, binary = cv2.threshold(mask_chip, 127, 255, cv2.THRESH_BINARY)
    n, _, stats, _ = cv2.connectedComponentsWithStats(binary, connectivity=8)
    h, w = binary.shape
    boxes = []
    for i in range(1, n):  # 0 == background
        x, y, bw, bh, area = stats[i]
        if area < MIN_AREA_PX:
            continue
        cx = (x + bw / 2) / w
        cy = (y + bh / 2) / h
        boxes.append((cx, cy, bw / w, bh / h))
    return boxes


def process_tile(name: str, split: str) -> tuple[int, int]:
    img = cv2.imread(str(RAW / f"{name}.tif"), cv2.IMREAD_COLOR)
    mask = cv2.imread(str(RAW / f"{name}_gt.tif"), cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"missing image: {RAW / f'{name}.tif'}")
    if mask is None:
        raise FileNotFoundError(f"missing mask: {RAW / f'{name}_gt.tif'}")
    if img.shape[:2] != mask.shape[:2]:
        raise ValueError(f"shape mismatch for {name}: {img.shape} vs {mask.shape}")
    h, w = mask.shape
    n_chips = n_boxes = 0
    for r in range(0, h, CHIP):
        for c in range(0, w, CHIP):
            chip = img[r:r + CHIP, c:c + CHIP]
            mchip = mask[r:r + CHIP, c:c + CHIP]
            if chip.shape[0] < CHIP // 2 or chip.shape[1] < CHIP // 2:
                continue  # sliver at the edge — skip
            # 5000 % 1000 == 0, so every chip is exactly CHIP x CHIP and
            # chip_boxes() coordinates are already normalised to this chip.
            boxes = chip_boxes(mchip)
            stem = f"{name}_r{r}_c{c}"
            cv2.imwrite(
                str(OUT / "images" / split / f"{stem}.jpg"),
                chip,
                [cv2.IMWRITE_JPEG_QUALITY, 88],
            )
            with open(OUT / "labels" / split / f"{stem}.txt", "w") as f:
                for cx, cy, bw, bh in boxes:
                    f.write(f"0 {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}\n")
            n_chips += 1
            n_boxes += len(boxes)
    return n_chips, n_boxes


def main() -> int:
    for sub in ("images/train", "images/val", "labels/train", "labels/val"):
        (OUT / sub).mkdir(parents=True, exist_ok=True)
    (OUT / "data.yaml").write_text(DATA_YAML, encoding="utf-8")
    total = {"train": [0, 0], "val": [0, 0]}
    for name in TRAIN_TILES:
        c, b = process_tile(name, "train")
        total["train"][0] += c
        total["train"][1] += b
        print(f"  {name}: {c} chips, {b} building boxes (train)")
    for name in VAL_TILES:
        c, b = process_tile(name, "val")
        total["val"][0] += c
        total["val"][1] += b
        print(f"  {name}: {c} chips, {b} building boxes (val)")
    print(f"\nDone: train {total['train'][0]} chips / {total['train'][1]} boxes, "
          f"val {total['val'][0]} chips / {total['val'][1]} boxes -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
